export { TopBar } from './top-bar'
export { DashboardTopBar } from './dashboard-top-bar'
export { ProposalTabs, type SectionId } from './proposal-tabs'
export { Sidebar, type SidebarItem, type SidebarGroup } from './sidebar'
export { ProposalLayout, SECTION_GROUPS, SECTION_DEFAULT_VIEWS } from './proposal-layout'
