'use client'

import { useState } from 'react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { StatusBadge } from '@/components/shared/status-badge'
import { Copy, Check, CheckCircle2 } from 'lucide-react'
import type { BOEArtifactDetail } from '@/hooks/use-boe-artifacts'

interface ArtifactProvenanceHeaderProps {
  artifact: BOEArtifactDetail
}

/**
 * Provenance header for artifact viewer.
 * Displays hash, engine version, generated by/when, and conservation status.
 * This is the "trust presentation" per the contract.
 */
export function ArtifactProvenanceHeader({ artifact }: ArtifactProvenanceHeaderProps) {
  const [copiedHash, setCopiedHash] = useState(false)

  const formatDate = (iso: string) => {
    return new Date(iso).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    })
  }

  const truncateHash = (hash: string) => {
    return `${hash.slice(0, 8)}...${hash.slice(-6)}`
  }

  const copyHash = async () => {
    await navigator.clipboard.writeText(artifact.contentHash)
    setCopiedHash(true)
    setTimeout(() => setCopiedHash(false), 2000)
  }

  const content = artifact.content
  const allConserved = content?.conservation?.allConserved ?? false

  return (
    <Card className="p-4 bg-gray-50">
      <div className="flex flex-wrap items-start gap-6">
        {/* Status + Hash */}
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <StatusBadge
              status={artifact.status as 'generated' | 'superseded'}
            />
            <span className="text-xs text-muted-foreground">Artifact</span>
          </div>
          <div className="flex items-center gap-1">
            <code className="text-xs font-mono bg-white px-2 py-1 rounded border">
              {truncateHash(artifact.contentHash)}
            </code>
            <Button
              variant="ghost"
              size="icon"
              className="h-6 w-6"
              onClick={copyHash}
              title="Copy full hash"
            >
              {copiedHash ? (
                <Check className="w-3 h-3 text-green-600" />
              ) : (
                <Copy className="w-3 h-3" />
              )}
            </Button>
          </div>
        </div>

        {/* Intelligence Version */}
        {artifact.intelligenceHash && (
          <div className="space-y-1">
            <p className="text-xs font-medium text-muted-foreground">
              Intelligence
            </p>
            <code className="text-xs font-mono bg-white px-2 py-1 rounded border block">
              {truncateHash(artifact.intelligenceHash)}
            </code>
          </div>
        )}

        {/* Engine Version */}
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground">Engine</p>
          <code className="text-xs font-mono bg-white px-2 py-1 rounded border block">
            v{artifact.engineVersion}
          </code>
        </div>

        {/* Generated By/When */}
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground">Generated</p>
          <p className="text-sm text-gray-900">
            {formatDate(artifact.generatedAt)}
          </p>
          {artifact.generatedByName && (
            <p className="text-xs text-muted-foreground">
              by {artifact.generatedByName}
            </p>
          )}
        </div>

        {/* Conservation Status */}
        <div className="space-y-1">
          <p className="text-xs font-medium text-muted-foreground">
            Conservation
          </p>
          <div className="flex items-center gap-1">
            {allConserved ? (
              <>
                <CheckCircle2 className="w-4 h-4 text-green-600" />
                <span className="text-sm text-green-700">
                  Cost + Fee = Total
                </span>
              </>
            ) : (
              <span className="text-sm text-amber-700">
                Conservation check failed
              </span>
            )}
          </div>
        </div>
      </div>
    </Card>
  )
}
